<?php
/**
 * Страница "Форма архивирования файлов / папок".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>File / folder archiving form</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/compress.png' ?>" />
    </div>
    <p>The form appears after clicking the <b>"Archive"</b> button on the toolbar for the list of files and folders.</p>
    <h2>Form fields</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Archive type.</b> You need to select the archive type with which the files will be compressed;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Archive name.</b> The name (file) of the archive without extension. Depending on the selected archive type, the corresponding file extension will be added to the archive name.</li>
    </ul>
</article>