<?php
/**
 * Страница "Форма архивирования файлов / папок".
 * 
 * Локализации по умолчанию.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>File / folder archiving form</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/compress.png' ?>" />
    </div>
    <p>The form appears after clicking the <b>"Archive"</b> button on the toolbar for the list of files and folders.</p>
    <h2>Form fields</h2>
    <ul class="g-help-list">
        <li><b>Archive type.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><b>Archive name.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</li>
    </ul>
</article>