<?php
/**
 * Страница "Форма архивирования файлов / папок".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Форма архивирования файлов / папок</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/compress.png' ?>" />
    </div>
    <p>Форма появляется после нажатия на кнопку <b>"Архивировать"</b> панели инструментов списка файлов и папок.</p>
    <h2>Поля формы</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Тип архива.</b> Необходимо выбрать тип архива с помощью которого, будет выполнено сжатие файлов;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Имя архива.</b> Имя (файла) архива без расширения. В зависимости от вабранного типа архива будет добавлено к имени архива соответствующие расширение файла.</li>
    </ul>
</article>