<?php
/**
 * Страница "Форма создания файла / папки".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Форма создания файла / папки</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <div>
            <img src="<?= $assetsUrl, '/help/create-file.png' ?>" />
        </div>
        <div>
            <img src="<?= $assetsUrl, '/help/create-folder.png' ?>" />
        </div>
    </div>
    <p>Форма появляется после нажатия на кнопку <b>"Создать папку"</b> или <b>"Создать файл"</b> панели инструментов списка файлов и папок.</p>
    <h2>Поля формы</h2>
    <ul class="g-help-list">
        <li><b>Название.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</li>
    </ul>
</article>