<?php
/**
 * Страница "Форма создания файла / папки".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>File / folder creation form</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <div>
            <img src="<?= $assetsUrl, '/help/create-file.png' ?>" />
        </div>
        <div>
            <img src="<?= $assetsUrl, '/help/create-folder.png' ?>" />
        </div>
    </div>
    <p>The form appears after clicking the <b>"Create folder"</b> or <b>"Create file"</b> button on the file and folder list toolbar.</p>
    <h2>Form fields</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Name.</b> The name of the file or folder being created.</li>
    </ul>
</article>