<?php
/**
 * Страница "Панель файлового менеджера".
 * 
 * Локализации по умолчанию.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>File manager panel</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/desk.png' ?>" />
    </div>
    <p>The file manager panel consists of two areas:</p>
    <ul>
        <li>Folder tree</li>
        <li>List (grid) of files and folders</li>
    </lu>

    <h2>Folder tree</h2>
    <p>The folder tree panel consists of a tree-like list of folders and a toolbar for performing operations on these folders..</p>
    <h3>Toolbar</h3>
    <ul class="g-help-list">
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-expand.svg' ?>)"></span> <b>Expand.</b> Expands all nodes of the folder tree;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-collapse.svg' ?>)"></span> <b>Collaplse.</b> Collapses all nodes of the folder tree;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-refresh.svg' ?>)"></span> <b>Refresh.</b> Refreshes all nodes of the folder tree.</li>
    </ul>

    <h2>List (grid) of files and folders</h2>
    <p>The file panel consists of a list/grid of files and a toolbar for performing operations on those files..</p>
    <h3>Toolbar</h3>
    <ul class="g-help-list">
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-home.svg' ?>)"></span> <b>The root folder.</b> Performs transition to the root folder;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-up.svg' ?>)"></span> <b>Go to the next level.</b> Moves to the parent folder (folder one level up);</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-create_folder.svg' ?>)"></span> <b>Create folder.</b> Shows a window for creating a folder;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-create_file.svg' ?>)"></span> <b>Create file.</b> Shows a window for creating a file;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-delete.svg' ?>)"></span> <b>Delete.</b> Deletes selected items (files, folders) with confirmation;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-refresh.svg' ?>)"></span> <b>Refresh.</b> Refreshes the list / grid of items (files, folders);</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-find.svg' ?>)"></span> <b>Search.</b> Shows a panel with the ability to search for files and folders;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-profile_on.svg' ?>)"></span> <b>Profiling.</b> Expands or collapses the Navigation Pane to display information about the selected file or folder;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-select.svg' ?>)"></span> <b>Select.</b> Selects all items (files, folders) in a list/grid;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-inselect.svg' ?>)"></span> <b>Invert selection.</b> Clears selection from already selected items (files, folders);</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-unselect.svg' ?>)"></span> <b>Remove selection.</b> Resets the selection of all items (files, folders) in the list/grid;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-upload.svg' ?>)"></span> <b>Upload.</b> Opens a window to download a file;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-download.svg' ?>)"></span> <b>Download.</b> Performs download of selected elements (files, folders). If there are several elements, they will be packed into an archive and downloaded;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-compress.svg' ?>)"></span> <b>Archive.</b> Performs archiving and downloading of selected items (files, folders);</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-extract.svg' ?>)"></span> <b>Extract.</b> Opens a window to perform unzipping of the selected file;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-rename.svg' ?>)"></span> <b>Rename.</b> Opens a window for renaming a file or folder;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-edit.svg' ?>)"></span> <b>Edit.</b> Opens a window for editing the selected file;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-view.svg' ?>)"></span> <b>View.</b> Opens a window to view the file;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-permissions.svg' ?>)"></span> <b>Permissions.</b> Opens a window for setting access to a file or folder;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-attributes.svg' ?>)"></span> <b>Information.</b> Opens a window with information about a file or folder;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-cut.svg' ?>)"></span> <b>Cut.</b> Copies the names of selected files and folders to the clipboard for further operations on them;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-copy.svg' ?>)"></span> <b>Copy.</b> Copies only those files and folders whose names are in the buffer;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-paste.svg' ?>)"></span> <b>Past.</b> Pastes (moves) only those files and folders whose names are in the clipboard;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-grid.svg' ?>)"></span> <b>View - Grid.</b> The file panel will be displayed in a grid format;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-list.svg' ?>)"></span> <b>View - List.</b> The file panel will be displayed as a list;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-info.svg' ?>)"></span> <b>Help.</b> Opens the help information window;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-settings.svg' ?>)"></span> <b>Settings.</b> Opens the file manager panel settings window.</li>
    </ul>
</article>