<?php
/**
 * Страница "Панель файлового менеджера".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Панель файлового менеджера</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/desk.png' ?>" />
    </div>
    <p>Панель файлового менеджера состоит из двух областей:</p>
    <ul>
        <li>Дерево папок</li>
        <li>Список (сетка) файлов и папок</li>
    </lu>

    <h2>Дерево папок</h2>
    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>
    <h3>Панель инструментов</h3>
    <ul class="g-help-list">
        <li><span class="g-icon g-icon_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-expand.svg' ?>)"></span> <b>Развернуть.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-collapse.svg' ?>)"></span> <b>Свернуть.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-refresh.svg' ?>)"></span> <b>Обновить.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</li>
    </ul>

    <h2>Список (сетка) файлов и папок</h2>
    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>
    <h3>Панель инструментов</h3>
    <ul class="g-help-list">
        <li><span class="g-icon g-icon_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-home.svg' ?>)"></span> <b>Корневая папка.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-up.svg' ?>)"></span> <b>На один уровень выше.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-create_folder.svg' ?>)"></span> <b>Создать папку.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-create_file.svg' ?>)"></span> <b>Создать файл.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-delete.svg' ?>)"></span> <b>Удалить.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-refresh.svg' ?>)"></span> <b>Обновить.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-find.svg' ?>)"></span> <b>Поиск.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-profile_on.svg' ?>)"></span> <b>Профилирование.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-select.svg' ?>)"></span> <b>Выделить всё.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-inselect.svg' ?>)"></span> <b>Инвертировать выделение.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-unselect.svg' ?>)"></span> <b>Убрать выделение.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-upload.svg' ?>)"></span> <b>Загрузить файл.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-download.svg' ?>)"></span> <b>Скачать.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-compress.svg' ?>)"></span> <b>Архивировать.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-extract.svg' ?>)"></span> <b>Разархивировать.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-rename.svg' ?>)"></span> <b>Переименовать.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-edit.svg' ?>)"></span> <b>Редактировать.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-view.svg' ?>)"></span> <b>Просмотреть.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-permissions.svg' ?>)"></span> <b>Права доступа.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-attributes.svg' ?>)"></span> <b>Информация.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-cut.svg' ?>)"></span> <b>Вырезать.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-copy.svg' ?>)"></span> <b>Копировать.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-paste.svg' ?>)"></span> <b>Вставить.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-grid.svg' ?>)"></span> <b>Вид - Сетка.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-list.svg' ?>)"></span> <b>Вид - Список.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-info.svg' ?>)"></span> <b>Помощь.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-settings.svg' ?>)"></span> <b>Настройки.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</li>
    </ul>
</article>