<?php
/**
 * Страница "Панель файлового менеджера".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Панель файлового менеджера</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/desk.png' ?>" />
    </div>
    <p>Панель файлового менеджера состоит из двух областей:</p>
    <ul>
        <li>Дерево папок</li>
        <li>Список (сетка) файлов и папок</li>
    </lu>

    <h2>Дерево папок</h2>
    <p>Панель дерева папок состоит из списка папок в виде дерева и панели инструментов для совершения операций над этими папкам.</p>
    <h3>Панель инструментов</h3>
    <ul class="g-help-list">
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-expand.svg' ?>)"></span> <b>Развернуть.</b> Разворачивает все узлы дерева папок;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-collapse.svg' ?>)"></span> <b>Свернуть.</b> Сворачивает все узлы дерева папок;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-refresh.svg' ?>)"></span> <b>Обновить.</b> Обновляет все узлы дерева папок.</li>
    </ul>

    <h2>Список (сетка) файлов и папок</h2>
    <p>Панель файлов состоит из списка / сетки файлов и панели инструментов для совершения операций над этими файлами.</p>
    <h3>Панель инструментов</h3>
    <ul class="g-help-list">
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-home.svg' ?>)"></span> <b>Корневая папка.</b> Выполняет переход в корневую папку;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-up.svg' ?>)"></span> <b>Перейти на уровень выше.</b> Выполняет переход в родительскую папку (папка на уровень выше);</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-create_folder.svg' ?>)"></span> <b>Создать папку.</b> Вызывает окно для создания папки;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-create_file.svg' ?>)"></span> <b>Создать файл.</b> Вызывает окно для создания файла;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-delete.svg' ?>)"></span> <b>Удалить.</b> Удаляет выделенные элементы (файлы, папки) с подтверждением;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-refresh.svg' ?>)"></span> <b>Обновить.</b> Обновляет список / сетку элементов (файлы, папки);</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-find.svg' ?>)"></span> <b>Поиск.</b> Показывает панель с возможностью поиска файлов и папок;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-profile_on.svg' ?>)"></span> <b>Профилирование.</b> Разворачивает или сворачивает Панель навигации для отображения информации о выбранном файле или папке;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-select.svg' ?>)"></span> <b>Выделить всё.</b> Выделяет все элементы (файлы, папки) в списке / сетке;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-inselect.svg' ?>)"></span> <b>Инвертировать выделение.</b> Сбрасывает выделение с уже выбранных элементов (файлов, папок);</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-unselect.svg' ?>)"></span> <b>Убрать выделение.</b> Сбрасывает выделение всех элементов (файлы, папки) в списке / сетке;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-upload.svg' ?>)"></span> <b>Загрузить файл.</b> Открывает окно для загрузки файла;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-download.svg' ?>)"></span> <b>Скачать.</b> Выполняет скачивание выбранных элементов (файлы, папки). Если элементов несколько, то они будут упакованы в архив и скачаны;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-compress.svg' ?>)"></span> <b>Архивировать.</b> Выполняет архивацию и скачивание выбранных элементов (файлы, папки);</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-extract.svg' ?>)"></span> <b>Разархивировать.</b> Открывает окно для выполнения разархивации выбранного файла;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-rename.svg' ?>)"></span> <b>Переименовать.</b> Открывает окно для переименования файла или папки;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-edit.svg' ?>)"></span> <b>Редактировать.</b> Открывает окно для редактирования выделенного файла;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-view.svg' ?>)"></span> <b>Просмотреть.</b> Открывает окно для просмотра файла;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-permissions.svg' ?>)"></span> <b>Права доступа.</b> Открывает окно для настройки доступа к файлу или папке;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-attributes.svg' ?>)"></span> <b>Информация.</b> Открывает окно с информацией о файле или папке;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-cut.svg' ?>)"></span> <b>Вырезать.</b> Копирует в буфер имена выбранных файлов и папок для дальнейшего выполнения операций над ними;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-copy.svg' ?>)"></span> <b>Копировать.</b> Копирует только те файлы и папки, имена которых находятся в буфере;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-paste.svg' ?>)"></span> <b>Вставить.</b> Вставляет (переносит) только те файлы и папки, имена которых находятся в буфере;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-list.svg' ?>)"></span> <b>Вид - Сетка.</b> Панель файлов будет отображаться в виде сетки;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-grid.svg' ?>)"></span> <b>Вид - Список.</b> Панель файлов будет отображаться в виде списка;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-info.svg' ?>)"></span> <b>Помощь.</b> Открывает окно справочной информации;</li>
        <li><span class="g-icon g-icon_size_16 g-icon-svg_size_16 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-settings.svg' ?>)"></span> <b>Настройки.</b> Открывает окно настроек панели файлового менеджера.</li>
    </ul>
</article>