<?php
/**
 * Страница "Панель файлового менеджера".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>File manager panel</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/desk.png' ?>" />
    </div>
    <p>The file manager panel consists of two areas:</p>
    <ul>
        <li>Folder tree</li>
        <li>List (grid) of files and folders</li>
    </lu>

    <h2>Folder tree</h2>
    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>
    <h3>Toolbar</h3>
    <ul class="g-help-list">
        <li><span class="g-icon g-icon_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-expand.svg' ?>)"></span> <b>Expand.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-collapse.svg' ?>)"></span> <b>Collaplse.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-refresh.svg' ?>)"></span> <b>Refresh.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</li>
    </ul>

    <h2>List (grid) of files and folders</h2>
    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>
    <h3>Toolbar</h3>
    <ul class="g-help-list">
        <li><span class="g-icon g-icon_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-home.svg' ?>)"></span> <b>The root folder.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-up.svg' ?>)"></span> <b>One level up.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-create_folder.svg' ?>)"></span> <b>Create folder.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-create_file.svg' ?>)"></span> <b>Create file.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-delete.svg' ?>)"></span> <b>Delete.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-refresh.svg' ?>)"></span> <b>Refresh.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-find.svg' ?>)"></span> <b>Search.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-profile_on.svg' ?>)"></span> <b>Profiling.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-select.svg' ?>)"></span> <b>Select.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-inselect.svg' ?>)"></span> <b>Invert selection.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-unselect.svg' ?>)"></span> <b>Remove selection.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-upload.svg' ?>)"></span> <b>Upload.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-download.svg' ?>)"></span> <b>Download.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-compress.svg' ?>)"></span> <b>Archive.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-extract.svg' ?>)"></span> <b>Extract.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-rename.svg' ?>)"></span> <b>Rename.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-edit.svg' ?>)"></span> <b>Edit.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-view.svg' ?>)"></span> <b>View.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-permissions.svg' ?>)"></span> <b>Permissions.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-attributes.svg' ?>)"></span> <b>Information.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-cut.svg' ?>)"></span> <b>Cut.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-copy.svg' ?>)"></span> <b>Copy.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-paste.svg' ?>)"></span> <b>Вставить.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-grid.svg' ?>)"></span> <b>View - Grid.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-list.svg' ?>)"></span> <b>View - List.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-info.svg' ?>)"></span> <b>Help.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><span class="g-icon g-icon_size_32 g-icon-svg_size_32 g-icon-m_color_neutral-dark" style="background-image: url(<?= $assetsUrl, '/images/toolbar/icon-settings.svg' ?>)"></span> <b>Settings.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</li>
    </ul>
</article>