<?php
/**
 * Страница "Форма редактирования файла".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Форма редактирования файла</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/edit.png' ?>" />
    </div>
    <p>Форма появляется после нажатия на кнопку <b>"Редактировать"</b> панели инструментов списка файлов и папок.</p>
    <p>Форма имеет текстовый редактор, предназначенный для изменения текста файла. В качестве редактора может использоваться виджет <a href="<?= $url('index', 'widget:gm.wd.codemirror') ?>">"CodeMirror"</a>, <a href="<?= $url('index', 'widget:gm.wd.tinymce') ?>">"TinyMCE"</a> и другие.</p>
</article>