<?php
/**
 * Страница "Форма редактирования файла".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>File editing form</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/edit.png' ?>" />
    </div>
    <p>The form appears after clicking on the <b>"Edit"</b> button on the toolbar for the list of files and folders.</p>
    <p>The form has a text editor designed to change the text of the file. A widget can be used as an editor <a href="<?= $url('index', 'widget:gm.wd.codemirror') ?>">"CodeMirror"</a>, <a href="<?= $url('index', 'widget:gm.wd.tinymce') ?>">"TinyMCE"</a> and others.</p>
</article>