<?php
/**
 * Страница "Форма извлечения файлов из архива".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Форма извлечения файлов из архива</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/extract.png' ?>" />
    </div>
    <p>Форма появляется после нажатия на кнопку <b>"Извлечь"</b> панели инструментов списка файлов и папок.</p>
    <h2>Поля формы</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Куда.</b> Необходимо выбрать вариант извлечения файлов из архива: "в отдельную папку", "в текущую папку";</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Имя папки.</b> Поле появляется после выбора варианта извлечения "в отдельную папку";</li>
        <li><span class="g-help-fld g-help-fld_checkbox"></span> <b>Флажок "удалить архив после извлечения".</b> Удаляет архив после извлечения файлов, если установлен флаг.</li>
    </ul>
</article>