<?php
/**
 * Страница "Форма извлечения файлов из архива".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Form for extracting files from archive</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/extract.png' ?>" />
    </div>
    <p>The form appears after clicking the <b>"Extract"</b> button on the toolbar for the list of files and folders.</p>
    <h2>Form fields</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Where.</b> You need to select the option for extracting files from the archive: "to a separate folder", "to the current folder";</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Folder name.</b> The field appears after selecting the extraction option "to a separate folder";</li>
        <li><span class="g-help-fld g-help-fld_checkbox"></span> <b>Checkbox "delete archive after extraction".</b> Deletes archive after extracting files if flag is set.</li>
    </ul>
</article>