<?php
/**
 * Страница "Форма настройки права доступа к файлу / папке".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Form for setting access rights to a file / folder</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/permissions.png' ?>" />
    </div>
    <p>The form appears after clicking on the <b>"Permissions"</b> button on the file and folder list toolbar.</p>
    <h2>Form fields</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_checkbox"></span> <b>Owner rights.</b> Set permissions (read, write, execute) for the owner;</li>
        <li><span class="g-help-fld g-help-fld_checkbox"></span> <b>Group rights.</b> Set permissions (read, write, execute) for the owner group;</li>
        <li><span class="g-help-fld g-help-fld_checkbox"></span> <b>Public rights.</b> Set permissions (read, write, execute) for everyone else;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Numeric value.</b> Numeric value obtained from setting permissions.</li>
    </ul>
</article>