<?php
/**
 * Страница "Форма изменения имени файла / папки".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Форма изменения имени файла / папки</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <div>
            <img src="<?= $assetsUrl, '/help/rename-folder.png' ?>" />
        </div>
        <div>
            <img src="<?= $assetsUrl, '/help/rename-file.png' ?>" />
        </div>
    </div>
    <p>Форма появляется после нажатия на кнопку <b>"Переименовать"</b> панели инструментов списка файлов и папок.</p>
    <h2>Поля формы</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Новое название.</b> Новое название файла или папки.</li>
    </ul>
</article>