<?php
/**
 * Страница "Форма изменения имени файла / папки".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>File / folder name change form</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <div>
            <img src="<?= $assetsUrl, '/help/rename-folder.png' ?>" />
        </div>
        <div>
            <img src="<?= $assetsUrl, '/help/rename-file.png' ?>" />
        </div>
    </div>
    <p>The form appears after clicking the <b>"Rename"</b> button on the file and folder list toolbar.</p>
    <h2>Form fields</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>New name.</b> New name of file or folder.</li>
    </ul>
</article>