<?php
/**
 * Страница "Форма загрузки файла".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>File upload form</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/upload.png' ?>" />
    </div>
    <p>The form appears after clicking on the <b>"Upload"</b> button on the toolbar for the list of files and folders.</p>
    <h2>Form fields/h2>
    <ul class="g-help-list">
        <li><b>File name.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</li>
    </ul>
</article>