<?php
/**
 * Страница "Форма загрузки файла".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>File upload form</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/upload.png' ?>" />
    </div>
    <p>The form appears after clicking on the <b>"Upload"</b> button on the toolbar for the list of files and folders.</p>
    <h2>Form fields/h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>File name.</b> Using the "Browse" button, you must select a file. The file will be uploaded according to the "resource upload parameters to the server".</li>
    </ul>
</article>