<?php
/**
 * Страница "Форма загрузки файла".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Форма загрузки файла</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/upload.png' ?>" />
    </div>
    <p>Форма появляется после нажатия на кнопку <b>"Загрузить"</b> панели инструментов списка файлов и папок.</p>
    <h2>Поля формы</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Имя файла.</b> С помощью кнопки "Обзор" необходимо выбрать файл. Загрузка файла будет выполнена согласно "параметрам загрузки ресурсов на сервер".</li>
    </ul>
</article>